version: '3.8'

services:
  # Backend (Laravel)
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"  # Expose Laravel server on port 8000
    volumes:
      - ./backend:/var/www/html  # Mount your Laravel project folder
    depends_on:
      - database

  # Frontend (Remix)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # Expose Remix app on port 3000
    volumes:
      - ./frontend:/app  # Mount your Remix project folder
    depends_on:
      - backend  # Ensure the backend is ready before starting frontend

  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

volumes:
  pgdata:
