version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"       
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"    
    volumes:
      - ./frontend:/usr/src/app  
      - /usr/src/app/node_modules
      - /usr/src/app/build

    depends_on:
      - backend

  db:
    image: postgres:15  
    container_name: db
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_DB=taskflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
